
  type
  // A Codepoint is a natively expressed (LE on Windows) 32-bit value
  //  identifying a unique Unicode codepoint and is an alias for the Utf32Char type.

    Codepoint   = Deltics.Strings.Types.Codepoint;
    PCodepoint  = Deltics.Strings.Types.PCodepoint;


  // Strings

    Utf8String    = Deltics.Strings.Types.Utf8String;
    UnicodeString = Deltics.Strings.Types.UnicodeString;
    AsciiString   = Deltics.Strings.Types.AsciiString;


  // Chars

    AsciiChar     = Deltics.Strings.Types.AsciiChar;
    Utf8Char      = Deltics.Strings.Types.Utf8Char;
    Utf16Char     = Deltics.Strings.Types.Utf16Char;
    Utf32Char     = Deltics.Strings.Types.Utf32Char;

    PAsciiChar    = Deltics.Strings.Types.PAsciiChar;
    PUtf8Char     = Deltics.Strings.Types.PUtf8Char;
    PUtf16Char    = Deltics.Strings.Types.PUtf16Char;
    PUtf32Char    = Deltics.Strings.Types.PUtf32Char;


  // Dynamic arrays of Character types

    AnsiCharArray   = Deltics.Strings.Types.AnsiCharArray;
    AsciiArray      = Deltics.Strings.Types.AsciiArray;
    CharArray       = Deltics.Strings.Types.CharArray;
    Utf8Array       = Deltics.Strings.Types.Utf8Array;
    Utf16Array      = Deltics.Strings.Types.Utf16Array;
    Utf32Array      = Deltics.Strings.Types.Utf32Array;
    WideCharArray   = Deltics.Strings.Types.WideCharArray;
    CodepointArray  = Deltics.Strings.Types.CodepointArray;


  // Dynamic arrays of String types

    AnsiStringArray     = Deltics.Strings.Types.AnsiStringArray;
    AsciiStringArray    = Deltics.Strings.Types.AsciiStringArray;
    StringArray         = Deltics.Strings.Types.StringArray;
    UnicodeStringArray  = Deltics.Strings.Types.UnicodeStringArray;
    Utf8StringArray     = Deltics.Strings.Types.Utf8StringArray;
    WideStringArray     = Deltics.Strings.Types.WideStringArray;
