
  type
  // A Codepoint is a natively expressed (LE on Windows) 32-bit value
  //  identifying a unique Unicode codepoint and is an alias for the Utf32Char type.

    Codepoint   = Deltics.StringTypes.Codepoint;
    PCodepoint  = Deltics.StringTypes.PCodepoint;


  // Strings

    Utf8String    = Deltics.StringTypes.Utf8String;
    UnicodeString = Deltics.StringTypes.UnicodeString;
    AsciiString   = Deltics.StringTypes.AsciiString;


  // Chars

    AsciiChar     = Deltics.StringTypes.AsciiChar;
    Utf8Char      = Deltics.StringTypes.Utf8Char;
    Utf16Char     = Deltics.StringTypes.Utf16Char;
    Utf32Char     = Deltics.StringTypes.Utf32Char;

    PAsciiChar    = Deltics.StringTypes.PAsciiChar;
    PUtf8Char     = Deltics.StringTypes.PUtf8Char;
    PUtf16Char    = Deltics.StringTypes.PUtf16Char;
    PUtf32Char    = Deltics.StringTypes.PUtf32Char;


  // Dynamic arrays of Character types

    AnsiCharArray   = Deltics.StringTypes.AnsiCharArray;
    AsciiArray      = Deltics.StringTypes.AsciiArray;
    CharArray       = Deltics.StringTypes.CharArray;
    Utf8Array       = Deltics.StringTypes.Utf8Array;
    Utf16Array      = Deltics.StringTypes.Utf16Array;
    Utf32Array      = Deltics.StringTypes.Utf32Array;
    WideCharArray   = Deltics.StringTypes.WideCharArray;
    CodepointArray  = Deltics.StringTypes.CodepointArray;


  // Dynamic arrays of String types

    AnsiStringArray     = Deltics.StringTypes.AnsiStringArray;
    AsciiStringArray    = Deltics.StringTypes.AsciiStringArray;
    StringArray         = Deltics.StringTypes.StringArray;
    UnicodeStringArray  = Deltics.StringTypes.UnicodeStringArray;
    Utf8StringArray     = Deltics.StringTypes.Utf8StringArray;
    WideStringArray     = Deltics.StringTypes.WideStringArray;


  // Sets

    AnsiCharSet   = Deltics.StringTypes.AnsiCharSet;
    AsciiCharSet  = Deltics.StringTypes.AsciiCharSet;

